[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
installers = ["shell", "powershell"]
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
install-path = "CARGO_HOME"
hosting = "github"
install-updater = false
github-attestations = true
post-announce-jobs = ["./mcpb-release"]
include = ["THIRD-PARTY-LICENSES.html", "dictionaries"]

[dist.github-custom-job-permissions]
mcpb-release = { contents = "write", attestations = "write", id-token = "write" }

[dist.github-action-commits]
"actions/attest" = "1e69f48acb82d1966a394da916b4c1698aa569d6"
"actions/checkout" = "d23441a48e516b6c34aea4fa41551a30e30af803"
"actions/download-artifact" = "3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"
"actions/upload-artifact" = "043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"
